
server:
  port: 8081
spring:
  datasource:
    username: root
    password: p
    url: jdbc:mysql://localhost:3306/stu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8

  mail:
    host: smtp.qq.com
    username: 2134356214@qq.com
    password: ckhvaflqxmaxfech
    properties:
      from: 2134356214@qq.com


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      manager:
        mapper: debug


